BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Patient] ADD [CreateAt] DATETIME2 NOT NULL CONSTRAINT [Patient_CreateAt_df] DEFAULT CURRENT_TIMESTAMP,
[UpdateAt] DATETIME2 NOT NULL CONSTRAINT [Patient_UpdateAt_df] DEFAULT CURRENT_TIMESTAMP;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
